[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[registries.crates-io]
protocol = "sparse"

[term.progress]
when = "always"
width = 80